{% set name = "hyperspy_gui_ipywidgets" %}
{% set version = "1.5.0" %}
{% set sha256 = "e5b59279ac15cec93c7699295bb904d967a545bf3e341356ffc6753f4c7f3a2d" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

outputs:
  - name: {{ name|lower }}
    script: build_base.sh
    requirements:
      host:
        - python >=3.7
        - pip

      run:
        - python >=3.7
        - link-traits
        - hyperspy-base >=1.7.0
        - ipywidgets >=7.0

    test:
      imports:
        - hyperspy_gui_ipywidgets
      commands:
        - pip check
        - export MPLBACKEND="agg"
        - pytest --pyargs hyperspy_gui_ipywidgets
      requires:
        - pip
        - pytest

  - name: hyperspy-gui-ipywidgets
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('hyperspy_gui_ipywidgets', max_pin="x.x.x") }}
    test:
      imports:
        - hyperspy_gui_ipywidgets

about:
  home: https://github.com/hyperspy/hyperspy_gui_ipywidgets
  license: GPL-3.0-or-later
  summary: ipywidgets GUI elements for HyperSpy.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
    - ericpre
