{% set name = "hyperspy-gui-ipywidgets" %}
{% set filename = "hyperspy_gui_ipywidgets" %}
{% set version = "1.3.0" %}
{% set sha256 = "e2453811c6f30bcc0f3ee6eed7ea69acd59274a0a4213c68684ea61d4dbcaae6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  build:
    - python >=3.5
    - pip

  run:
    - python >=3.5
    - link-traits
    - hyperspy-base >=1.6
    - ipywidgets >=6.0

test:
  imports:
    - hyperspy_gui_ipywidgets

  commands:
    - export MPLBACKEND="agg"
    - pytest --pyargs hyperspy_gui_ipywidgets

  requires:
    - pytest

about:
  home: https://github.com/hyperspy/hyperspy_gui_ipywidgets
  license: GPL v3
  summary: ipywidgets GUI elements for HyperSpy.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
