{% set name = "hyperspy-gui-ipywidgets" %}
{% set filename = "hyperspy_gui_ipywidgets" %}
{% set version = "2.0" %}
{% set sha256 = "dad10e92bf9d27aa9442e7c1ca553f1ee77e50ad0ba16036a9cab7d3a47f3acf" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=64
    - setuptools-scm >=8

  run:
    - python >=3.8
    - link-traits
    - hyperspy-base >=2.0
    - ipywidgets >=7.0
    - ipympl

test:
  imports:
    - hyperspy_gui_ipywidgets

  commands:
    - export MPLBACKEND="agg"
    - pytest --pyargs hyperspy_gui_ipywidgets -k "not test_spikes_removal_tool"

  requires:
    - pytest

about:
  home: https://github.com/hyperspy/hyperspy_gui_ipywidgets
  license: GPL-3.0-or-later
  summary: ipywidgets GUI elements for HyperSpy.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
    - ericpre
