# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EtOgqIufjkC0Q7Qy2XkdRaKXGbvrp3XCJUZkTRvRz/dtNUC/ujoPtrBugq8/7ipVNSV2Q7Z9Q77QRHgoK7LdsnYZbC3OCJIZqYb0rkMmGEWVsdVleatajzoglw+hZ3qBiNM1Fkts++e1zQypMudnzvdAmaneCFQt6tvfgWg7fbj7rMZEAwN3G1LVcdkA64WxwGj4o5P/MuyOfpHaHIz00jjdWAO92D/JdrsbzLiq+qKWirUonHAKT/D/DtI46nARFkmezc9uTh11tF2aDfia2Y98Rei+TCrjRGX4I90nB/QkalMy0qWv8U1qa851xt5X2J0lkO7w52CsaMyqkQZjaFYEKRqanjcJhfTVi9+D8PBn98bhDVUTaPESA13Q7+TIMUzQbJJffIuHcmjM/JRzQqekROSic7bxz8bzVMIBXYqX9mTBA82+44TG0sIbvU+0m95WorweWCkBHGPjQBQ5bWsG8AIdjNKFTB0Vjk8AfIS8oUWAgYZ+9u7K/5q9xYM1Oh5/RFfELqEEmdVrk90oZsIqR+pMa/NroOBdE/3t5k0NrWLGCMbzoZRN2IAftOTq5Tdpc9LAB7EVHlX7G6DoMSahB+gC/WaMvp4zBWlMeOoB/V1Ymh/srTGvxL88lt+8qcXAkT5ivJ/EoU1s7cxApENSf65IQWHyd43piirepo0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
