travis:
  secure:
    BINSTAR_TOKEN: e/7q2+1Qz9r9GFs1S/KaHPESYvtxg5JBGSdYn78JHii9enzhhDHO3g1ha7DUMvmQvD2pgXqn88109L03LjjgQP3YA5tMqQLqlmlms/33KivNDqG4mZWwQnmviuWe/Z6Q82K81lxZTsKzngZDXCUHXs1SVmqoqPIxoWxv7siUqVSWiciAuil/VCckvzZsEXkMISjrj+kyGQ9NiJxenan3F7wii8aprTCMqHlct5pwGG+YO/3FJOgNYW9EMuAYWu/OUSq9X9jneklAJEiHpAHs4+ceX6/9lvfuKLO2fU5+UndjqkKZ85g3JqG/SnCx54YYQDKXCCO3frVE5Ipuyi20xk6JTCLhAy+NCX1H3TwEAsm4OSr9L3ZDTwXa1G1Byne1A3ZErmThs5l3okpqAZkeM1ze+MeHNpNPhGQ+7gIxAi0tOhjXr34pOcUJRH9gES437f8Tab66+GV2A+sHNAf7tXP9AGJ65/1uvGQbSkCdufzbPvwY5KrywMx2Mr6k1XFusq91Jpj04rsa3kGkeh79rrLg8V+dsMFwT6Hb8RnyjcGwawEg2uRcBTnfsUI97boNBnRA4ur+uFAFVT1O8EEZ7YVt0bxGl+8VpyEUiIYuyK88ReX/OiqKBTLfdMGxVfCSiWSptEc14znpjPa73IUBJT4hyCpzxqbkEPw+j3KHfjk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
